# Generated by Django 3.0.7 on 2020-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appA2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cno', models.IntegerField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
                ('pas', models.CharField(max_length=40)),
            ],
        ),
    ]
