# Generated by Django 3.0.7 on 2020-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appA2', '0002_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='cno',
            field=models.IntegerField(),
        ),
    ]
